routes/web.php
<?php

use App\Http\Controllers\CommunityController;
use App\Http\Controllers\CommunityPostController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostCommentController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', [HomeController::class, 'index'])->name('home');

Auth::routes(['verify' => true]);

Route::get('c/{slug}',
    [CommunityController::class, 'show'])
    ->name('communities.show');

Route::get('p/{post}',
    [CommunityPostController::class, 'show'])
    ->name('communities.posts.show');


Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::resources([
        'communities' => CommunityController::class,
        'communities.posts' => CommunityPostController::class,
        'posts.comments' => PostCommentController::class
    ],
        ['except' => ['show']]);

    Route::get('posts/{post_id}/vote/{vote}', [CommunityPostController::class, 'vote'])->name('post.vote');
    Route::post('posts/{post_id}/report', [CommunityPostController::class, 'report'])->name('post.report');
});

app/Models/Community.php
<?php

namespace App\Models;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Community extends Model
{
    use HasFactory, SoftDeletes, Sluggable;

    protected $fillable = ['user_id', 'name', 'slug', 'description'];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function topics(): BelongsToMany
    {
        return $this->belongsToMany(Topic::class);
    }

    public function posts(): HasMany
    {
        return $this->hasMany(Post::class);
    }

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

}

app/Http/Controllers/CommunityController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Community\StoreCommunityRequest;
use App\Http\Requests\Community\UpdateCommunityRequest;
use App\Models\Community;
use App\Models\Topic;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class CommunityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $communities = Community::where('user_id', auth()->id())->get();

        return view('communities.index', compact('communities'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreCommunityRequest $request
     * @return RedirectResponse
     */
    public function store(StoreCommunityRequest $request)
    {
        $community = Community::create($request->validated() + ['user_id' => auth()->id()]);
        $community->topics()->attach($request->topics);

        return to_route('communities.show', $community);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        $topics = Topic::all();
        return view('communities.create', compact('topics'));
    }

    /**
     * Display the specified resource.
     *
     * @param $slug
     * @return Application|Factory|View
     */
    public function show($slug)
    {
        $community=Community::where('slug', $slug)->firstOrFail();
        $query = $community->posts()->with('postVotes');

        if (request('sort', '') == 'popular') {
            $query->orderBy('votes', 'DESC');
        } else {
            $query->latest('id');
        }
        $posts = $query->paginate(10);

        return view('communities.show', compact('community', 'posts'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Community $community
     * @return Application|Factory|View
     */
    public function edit(Community $community)
    {
        if ($community->user_id != auth()->id()) {
            abort(403);
        }
        $topics = Topic::all();
        $community->load('topics');
        return view('communities.edit', compact('community', 'topics'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateCommunityRequest $request
     * @param Community $community
     * @return RedirectResponse
     */
    public function update(UpdateCommunityRequest $request, Community $community)
    {
        if ($community->user_id != auth()->id()) {
            abort(403);
        }

        $community->update($request->validated());
        $community->topics()->sync($request->topics);

        return to_route('communities.index')->with(['alert' => 'alert-info', 'message' => 'Successfully Updated!']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Community $community
     * @return RedirectResponse
     */
    public function destroy(Community $community)
    {
        if ($community->user_id != auth()->id()) {
            abort(403);
        }

        $community->delete();

        return to_route('communities.index')
            ->with(['alert' => 'alert-danger', 'message' => 'Successfully Deleted!']);
    }
}

resources/views/communities/create.blade.php
@extends('layouts.app')

@section('content')
                <div class="card">
                    <div class="card-header">{{ __('New Community') }}</div>

                    <div class="card-body">

                        <form method="POST" action="{{ route('communities.store') }}">
                            @csrf

                            <div class="row mb-3">
                                <label for="name" class="col-md-4 col-form-label text-md-end">{{ __('Name') }}*</label>

                                <div class="col-md-6">
                                    <input id="name" type="text"
                                           class="form-control @error('name') is-invalid @enderror" name="name"
                                           value="{{ old('name') }}" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="description"
                                       class="col-md-4 col-form-label text-md-end">{{ __('Description') }}*</label>

                                <div class="col-md-6">
                                    <textarea class="form-control @error('description') is-invalid @enderror"
                                              name="description" id="description"
                                              >{{old('description')}}</textarea>

                                    @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>


                            <div class="row mb-3">
                                <label for="topics"
                                       class="col-md-4 col-form-label text-md-end">{{ __('Topics') }}</label>
                                <div class="col-md-6">

                                    <select class="form-control select2" name="topics[]" multiple id="topics">
                                        @foreach($topics as $topic)
                                            <option value="{{$topic->id}}">{{$topic->name}} </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Create Community') }}
                                    </button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
@endsection

resources/views/communities/edit.blade.php
@extends('layouts.app')

@section('content')
                <div class="card">
                    <div class="card-header">{{ __('Edit Community') }}</div>

                    <div class="card-body">

                        <form method="POST" action="{{ route('communities.update', $community) }}">
                            @csrf
                            @method('PUT')

                            <div class="row mb-3">
                                <label for="name" class="col-md-4 col-form-label text-md-end">{{ __('Name') }}*</label>

                                <div class="col-md-6">
                                    <input id="name" type="text"
                                           class="form-control @error('name') is-invalid @enderror" name="name"
                                           value="{{ old('name', $community->name )}}" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="description"
                                       class="col-md-4 col-form-label text-md-end">{{ __('Description') }}*</label>

                                <div class="col-md-6">
                                    <textarea class="form-control @error('description') is-invalid @enderror"
                                              name="description" id="description"
                                              >{{old('description', $community->description)}}</textarea>

                                    @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>


                            <div class="row mb-3">
                                <label for="topics"
                                       class="col-md-4 col-form-label text-md-end">{{ __('Topics') }}</label>
                                <div class="col-md-6">

                                    <select class="form-control select2" name="topics[]" multiple id="topics">
                                        @foreach($topics as $topic)
                                            <option value="{{$topic->id}}" @if($community->topics->contains($topic->id)) selected @endif>{{$topic->name}} </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Update Community') }}
                                    </button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
@endsection

resources/views/communities/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">{{ __('My Communities') }}</div>

        <div class="card-body">
            @if(session('message'))
                <div class="alert {{session('alert')}}">{{session('message')}}</div>
                <br/>
            @endif
            <a href="{{route('communities.create')}}" class="btn btn-primary">New Community</a>
            <br/><br/>
            <table class="table">
                <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach($communities as $community)
                    <tr>
                        <td>
                            <a href="{{route('communities.show', $community)}}">{{$community->name}}</a>
                        </td>
                        <td>
                            <a href="{{route('communities.edit', $community)}}"
                               class="btn btn-sm btn-primary">Edit</a>
                            <form action="{{route('communities.destroy', $community)}}" method="POST"
                                  class="d-inline">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-sm btn-danger"
                                        onclick="return confirm('Are You Sure?')">Delete
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

        </div>
    </div>
@endsection

resources/views/communities/show.blade.php
@extends('layouts.app')

@section('content')
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-8">
                                <h1>{{ $community->name }}</h1>
                            </div>
                            <div class="col-4 text-end">
                                <a href="{{route('communities.show', $community)}}"
                                   @if(request('sort', '')=='') class="fs-4" @endif
                                >Newest Posts</a>
                                <br/>
                                <a href="{{route('communities.show', $community)}}?sort=popular"
                                   @if(request('sort', '')=='popular')class="fs-4"@endif>Popular Posts
                                    </a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <a href="{{route('communities.posts.create', $community)}}" class="btn btn-primary">Add
                            Post</a>
                        <br/><br/>

                        @forelse($posts as $post)
                            <div class="row">
                                @livewire('post-votes',['post'=>$post])

                                <div class="col-11">
                                    <a href="{{route('communities.posts.show',$post)}}">
                                        <h2>{{$post->title}}</h2></a>
                                    <p>{{$post->created_at->diffForHumans()}}</p>
                                    <p>{{Str::words($post->post_text, 10)}}</p>
                                </div>
                            </div>
                            <hr/>
                        @empty
                            No Posts Found!
                        @endforelse

                        {{$posts->links()}}

                    </div>
                </div>
@endsection